### ISSUE TITLE
Total number of workshops in plots seems incorrect

### ISSUE THREAD

**Issue by tracykteal** [carpentries/amy-feeds#10]
In the 'number of workshops per year' and 'workshops over time' plots, I don't think the total is correct, because it's less than the sum of the SWC, DC and LC workshops.

**Comment by tracykteal** [comment]
Also, the numbers don't seem to match what's in AMY. For example in 2018, pulling those numbers from the 'All activity over time' page, for 2018, it's 

Number of SWC workshops: | 309
Number of DC workshops | 125
Number of LC workshops | 32
Number of all Carpentries workshops | 466

**Comment by fmichonneau** [comment]
* I don't see the difference in numbers you mention in the first comment. The total is computed directly from the numbers of each workshop so it should add up (but bugs are always possible :slightly_smiling_face:)

* The difference with AMY might come from fact that the query we are using filters out some workshops and AMY might not use the exact same query. For instance, we don't include workshops with the tags "stalled", "hackathon", "canceled", or workshops for which we don't have an URL (this should probably be removed). We also didn't include workshops with the tag "unresponsive" but I just removed that.

**Comment by fmichonneau** [comment]
I think I now see the issue your described about the numbers not adding up and I found the source of the bug. I'll update soon.

**Comment by tracykteal** [comment]
No big hurry on the update. Just wanted to note the issue, so we can sort out which numbers are correct. As an example these are the numbers I get from AMY for 2018. 

<img width="447" alt="Screen Shot 2019-07-09 at 5 48 19 AM" src="https://user-images.githubusercontent.com/889238/60894056-d4855980-a216-11e9-9bad-e76c350cb612.png">

**Comment by fmichonneau** [comment]
closing in favor of #11
